name: Automation script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Automation_UI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: install requirments
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk wget maven
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

      - name: clone repo
        run: |
          git clone https://github.com/Gpsgamers/OTF_script.git

      - name: run script
        run: |
          cd OTF_script
          mvn clean
          mvn test -X

      - name: Create artifact folder
        run: |
          mkdir -p output
          echo "Sample artifact content" > output/info.txt   

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: my-artifact
          path: output/
          
      - name: deployment
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan gh-pages
          cd output
          git add .
          git commit -m "Deploy JMeter report"
          git push --force origin gh-pages
